#!/bin/bash
#
# git parsing functions

git_issues_from_last_commit() {
    issues=$(
        git log -1 HEAD \
            | grep -E "[A-Z,0-9]+-[0-9]+" -o \
            | jq -R -s -c 'split("\n")' \
          )
    # repipe to get rid of empty string because of trailing newline
    issues=$(echo $issues | jq -c '.[:-1]')
    # return
    echo "$issues"
}

git_issues_from_current_branch() {
    issues=$(
        git branch --show-current \
            | grep -E "[A-Z,0-9]+-[0-9]+" -o \
            | jq -R -s -c 'split("\n")' \
          )
    # repipe to get rid of empty string because of trailing newline
    issues=$(echo $issues | jq -c '.[:-1]')
    # return
    echo "$issues"
}
