#!/bin/sh
#
# After the entire commit process is completed, the post-commit hook runs. It
# doesn’t take any parameters, but you can easily get the last commit by running
# git log -1 HEAD. Generally, this script is used for notification or something
# similar.
#
# To enable this hook, rename this file to "post-commit".

HOOK=${0##*/}
SCRIPT_PATH=${0%/*}

# load helpers
. "$SCRIPT_PATH"/git-parser

# send event to activity watch
event=$(jq -c <<EOF
{
  "timestamp": "$(date --iso-8601=s --utc)",
  "data": {
    "hook": "$HOOK",
    "branch": "$(git_current_branch)",
    "summary": "$(git_title_from_last_commit)",
    "issues": $(git_issues_from_last_commit)
  }
}
EOF
     )
"$SCRIPT_PATH"/aw-event-create "$event"
